baseurl = "https://example.com/"
# remember trailing / at end of baseurl
languageCode = "fr-fr"
title = "HELLO GOOGLE ðŸ’–"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 50
theme = "sublime"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Pierrick Deniel"
	description = "à¸ªà¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¸ªà¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰ ê™¬ HELLO GOOGLE ê™¬ ONLY CRAPPY SEO TEST HERE ê™¬ à¸ªà¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¸ªà¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰à¹‰"
	copyright = ""

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "nwr"
	older = "oldr"

	pageNotFoundTitle = "Page non trouvÃ©e"
	pageNotFoundSubtitle = "Toi t'es <br>perdu."

[params.offcanvas]
	# Menu items
	title = "62 4b 4e"
	bio = "44Â°50.4264â€² - 0Â°34.83â€²"
	bio2 = "01100010 01101111 01110010 01100100 01100101 01100001 01110101 01111000"
	subscribe = "S'abonner"
	followme = "Contact"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "twitter"
		url = "https://twitter.com/bKN____"
